<?php
$content = file_get_contents('app/controllers/Patientdashboard.php');

$search = "            \$this->db->bind(':uid', \$_SESSION['user_id']);\n            \n            // Convert empty string for dob to null\n            \$dob = empty(trim(\$_POST['dob'] ?? '')) ? null : trim(\$_POST['dob'] ?? '');\n            \$this->db->bind(':dob', \$dob);\n            \n            \$gender = empty(trim(\$_POST['gender'] ?? '')) ? null : trim(\$_POST['gender'] ?? '');\n            \$this->db->bind(':gender', \$gender);\n            \n            \$this->db->bind(':blood_group', trim(\$_POST['blood_group'] ?? ''));\n            \$this->db->bind(':allergies', trim(\$_POST['allergies'] ?? ''));\n            \$this->db->bind(':medical_history', trim(\$_POST['medical_history'] ?? ''));\n            \$this->db->bind(':emergency_contact', trim(\$_POST['emergency_contact'] ?? ''));\n\n            if (\$this->db->execute()) {\n                \$data['success_msg'] = 'Profile updated successfully.';\n            }";

$replace = "            // Validate inputs\n            \$data['error_msg'] = '';\n            if(!empty(\$_POST['dob'])) {\n                \$date_err = Validator::date(\$_POST['dob']);\n                if(!empty(\$date_err)) \$data['error_msg'] = \$date_err;\n            }\n\n            if(empty(\$data['error_msg'])) {\n                \$this->db->bind(':uid', \$_SESSION['user_id']);\n                \n                // Convert empty string for dob to null\n                \$dob = empty(trim(\$_POST['dob'] ?? '')) ? null : trim(\$_POST['dob'] ?? '');\n                \$this->db->bind(':dob', \$dob);\n                \n                \$gender = empty(trim(\$_POST['gender'] ?? '')) ? null : trim(\$_POST['gender'] ?? '');\n                \$this->db->bind(':gender', \$gender);\n                \n                \$this->db->bind(':blood_group', trim(\$_POST['blood_group'] ?? ''));\n                \$this->db->bind(':allergies', trim(\$_POST['allergies'] ?? ''));\n                \$this->db->bind(':medical_history', trim(\$_POST['medical_history'] ?? ''));\n                \$this->db->bind(':emergency_contact', trim(\$_POST['emergency_contact'] ?? ''));\n\n                if (\$this->db->execute()) {\n                    \$data['success_msg'] = 'Profile updated successfully.';\n                }\n            }";

$content = str_replace($search, $replace, $content);

file_put_contents('app/controllers/Patientdashboard.php', $content);
