<?php
$content = file_get_contents('app/controllers/Auth.php');

$search1 = "            // Validate Email\n            if(empty(\$data['email'])) {\n                \$data['email_err'] = 'Please enter email';\n            }";
$replace1 = "            // Validate Email\n            if(empty(\$data['email'])) {\n                \$data['email_err'] = 'Please enter email';\n            } else {\n                \$email_err = Validator::email(\$data['email']);\n                if(!empty(\$email_err)) {\n                    \$data['email_err'] = \$email_err;\n                }\n            }";
$content = preg_replace('/' . preg_quote($search1, '/') . '/', $replace1, $content, 1);

$search2 = "            // Validate Email\n            if(empty(\$data['email'])) {\n                \$data['email_err'] = 'Please enter email';\n            } else {\n                // Check email\n                if(\$this->userModel->findUserByEmail(\$data['email'])) {\n                    \$data['email_err'] = 'Email is already taken';\n                }\n            }";
$replace2 = "            // Basic required validation\n            \$required_errors = Validator::required(['first_name', 'last_name', 'email', 'password', 'confirm_password'], \$_POST);\n            if(!empty(\$required_errors)) {\n                if(isset(\$required_errors['first_name'])) \$data['first_name_err'] = \$required_errors['first_name'];\n                if(isset(\$required_errors['last_name'])) \$data['last_name_err'] = \$required_errors['last_name'];\n                if(isset(\$required_errors['email'])) \$data['email_err'] = \$required_errors['email'];\n                if(isset(\$required_errors['password'])) \$data['password_err'] = \$required_errors['password'];\n                if(isset(\$required_errors['confirm_password'])) \$data['confirm_password_err'] = \$required_errors['confirm_password'];\n            }\n\n            // Validate Email\n            if(empty(\$data['email_err'])) {\n                \$email_err = Validator::email(\$data['email']);\n                if(!empty(\$email_err)) {\n                    \$data['email_err'] = \$email_err;\n                } elseif(\$this->userModel->findUserByEmail(\$data['email'])) {\n                    \$data['email_err'] = 'Email is already taken';\n                }\n            }";
$content = preg_replace('/' . preg_quote($search2, '/') . '/', $replace2, $content, 1);

$search3 = "            // Validate Password\n            if(empty(\$data['password'])) {\n                \$data['password_err'] = 'Please enter password';\n            } elseif(strlen(\$data['password']) < 6) {\n                \$data['password_err'] = 'Password must be at least 6 characters';\n            }";
$replace3 = "            // Validate Password\n            if(empty(\$data['password_err'])) {\n                \$password_err = Validator::password(\$data['password']);\n                if(!empty(\$password_err)) {\n                    \$data['password_err'] = \$password_err;\n                }\n            }";
$content = preg_replace('/' . preg_quote($search3, '/') . '/', $replace3, $content, 1); // Replace only first occurrence in patient register

$search4 = "            // Validate Clinic Name\n            if(empty(\$data['clinic_name'])) {\n                \$data['clinic_name_err'] = 'Please enter clinic name';\n            }";
$replace4 = "            // Basic required validation\n            \$required_errors = Validator::required(['clinic_name', 'email', 'phone', 'address', 'city', 'state', 'zip', 'license_number', 'specialty', 'password', 'confirm_password'], \$_POST);\n            if(!empty(\$required_errors)) {\n                if(isset(\$required_errors['clinic_name'])) \$data['clinic_name_err'] = \$required_errors['clinic_name'];\n                if(isset(\$required_errors['email'])) \$data['email_err'] = \$required_errors['email'];\n                if(isset(\$required_errors['phone'])) \$data['phone_err'] = \$required_errors['phone'];\n                if(isset(\$required_errors['address'])) \$data['address_err'] = \$required_errors['address'];\n                if(isset(\$required_errors['city'])) \$data['city_err'] = \$required_errors['city'];\n                if(isset(\$required_errors['state'])) \$data['state_err'] = \$required_errors['state'];\n                if(isset(\$required_errors['zip'])) \$data['zip_err'] = \$required_errors['zip'];\n                if(isset(\$required_errors['license_number'])) \$data['license_number_err'] = \$required_errors['license_number'];\n                if(isset(\$required_errors['specialty'])) \$data['specialty_err'] = \$required_errors['specialty'];\n                if(isset(\$required_errors['password'])) \$data['password_err'] = \$required_errors['password'];\n                if(isset(\$required_errors['confirm_password'])) \$data['confirm_password_err'] = \$required_errors['confirm_password'];\n            }";
$content = str_replace($search4, $replace4, $content);

$search5 = "            // Validate Email\n            if(empty(\$data['email'])) {\n                \$data['email_err'] = 'Please enter email';\n            } else {\n                // Check email\n                if(\$this->userModel->findUserByEmail(\$data['email'])) {\n                    \$data['email_err'] = 'Email is already taken';\n                }\n            }";
$replace5 = "            // Validate Email\n            if(empty(\$data['email_err'])) {\n                \$email_err = Validator::email(\$data['email']);\n                if(!empty(\$email_err)) {\n                    \$data['email_err'] = \$email_err;\n                } elseif(\$this->userModel->findUserByEmail(\$data['email'])) {\n                    \$data['email_err'] = 'Email is already taken';\n                }\n            }";
$content = str_replace($search5, $replace5, $content);

$search6 = "            // Validate Phone\n            if(empty(\$data['phone'])) {\n                \$data['phone_err'] = 'Please enter phone number';\n            }";
$replace6 = "            // Validate Phone\n            if(empty(\$data['phone_err'])) {\n                \$phone_err = Validator::phone(\$data['phone']);\n                if(!empty(\$phone_err)) {\n                    \$data['phone_err'] = \$phone_err;\n                }\n            }";
$content = str_replace($search6, $replace6, $content);

$content = preg_replace('/' . preg_quote($search3, '/') . '/', $replace3, $content);

file_put_contents('app/controllers/Auth.php', $content);
